development:
  adapter: postgresql
  encoding: unicode
  database: top50_development
  username: octo
  password: 123456
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
